[project]
name = "agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ximeng", email = "ximeng0329@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "minsearch>=0.2.0",
    "openai>=3.8.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "sqlitesearch>=0.3.0",
]

[project.scripts]
agentic-ai = "agentic_ai:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
